/* Copyright (C) 2023-2026 QuantumNous
SPDX-License-Identifier: AGPL-3.0-or-later */
import { Dialog } from '@base-ui/react/dialog'
import { Bookmark, Download, Maximize2, MoreHorizontal, X } from 'lucide-react'
import { useEffect, useRef, useState, type ReactNode } from 'react'
import { useTranslation } from 'react-i18next'

import type { MediaKind } from '../contracts'
import { DEMO_IMAGE_SAMPLES, DEMO_MEDIA } from '../fixtures'

export function SampleArtwork(props: {
  kind: MediaKind
  active: boolean
  mobileResultVisible: boolean
  onOpenWorks: () => void
  taskStatus?: ReactNode
}) {
  const { t } = useTranslation()
  const [selected, setSelected] = useState(0)
  const videoRef = useRef<HTMLVideoElement>(null)
  const isImage = props.kind === 'image'
  const sample = DEMO_IMAGE_SAMPLES[selected]
  const media = isImage ? sample : DEMO_MEDIA.video

  useEffect(() => {
    const video = videoRef.current
    const narrowScreen = window.matchMedia('(max-width: 760px)')
    const pauseHiddenVideo = () => {
      if (
        video &&
        !video.paused &&
        (!props.active ||
          document.hidden ||
          (narrowScreen.matches && !props.mobileResultVisible))
      ) {
        video.pause()
      }
    }
    pauseHiddenVideo()
    narrowScreen.addEventListener('change', pauseHiddenVideo)
    document.addEventListener('visibilitychange', pauseHiddenVideo)
    return () => {
      narrowScreen.removeEventListener('change', pauseHiddenVideo)
      document.removeEventListener('visibilitychange', pauseHiddenVideo)
      if (video && !video.paused) video.pause()
    }
  }, [props.active, props.mobileResultVisible])

  return (
    <section
      className='studio-result studio-panel studio-sample-result'
      aria-label={t('Creation result')}
    >
      <Dialog.Root>
        <div className='studio-sample-toolbar'>
          <h2 className='studio-result-label'>{t('Sample artwork')}</h2>
          {isImage && (
            <Dialog.Trigger
              className='studio-icon-button studio-enlarge'
              aria-label={t('Enlarge image')}
            >
              <Maximize2 size={18} aria-hidden='true' />
            </Dialog.Trigger>
          )}
        </div>
        {props.taskStatus}
        <div className={`studio-media-stage studio-media-stage--${props.kind}`}>
          {isImage ? (
            <img
              className='studio-result-image'
              src={media.src}
              alt={t('Image demonstration sample')}
              width={sample.width}
              height={sample.height}
            />
          ) : (
            <video
              ref={videoRef}
              className='studio-result-video'
              src={media.src}
              poster={DEMO_MEDIA.video.poster}
              controls
              playsInline
              preload='metadata'
              controlsList='nodownload'
              aria-label={t('Video demonstration sample')}
            />
          )}
        </div>
        {isImage && (
          <Dialog.Portal>
            <Dialog.Backdrop className='studio-modal-backdrop' />
            <Dialog.Popup className='studio-lightbox'>
              <div className='studio-lightbox-header'>
                <Dialog.Title>{t('Sample artwork')}</Dialog.Title>
                <Dialog.Close
                  className='studio-icon-button'
                  aria-label={t('Close')}
                >
                  <X size={20} />
                </Dialog.Close>
              </div>
              <Dialog.Description className='studio-sr-only'>
                {t('Fixed demo media · Not generated by the selected model')}
              </Dialog.Description>
              <img src={media.src} alt={t('Image demonstration sample')} />
            </Dialog.Popup>
          </Dialog.Portal>
        )}
      </Dialog.Root>
      <div className='studio-sample-meta'>
        <div className='studio-artwork-info'>
          <h3>{isImage ? t(sample.title) : t('A quiet moment after dark')}</h3>
          <p>
            {isImage
              ? t(sample.description)
              : t('A local playback sample. Not a model benchmark.')}
          </p>
        </div>
        <div className='studio-result-actions'>
          <button
            type='button'
            className='studio-secondary-button'
            disabled
            aria-label={t('Keep in this browser')}
            title={t('Sample downloads are disabled in this design preview')}
          >
            <Bookmark size={16} aria-hidden='true' />
            {t('Save sample')}
          </button>
          <button
            type='button'
            className='studio-secondary-button'
            disabled
            aria-label={isImage ? t('Download image') : t('Download video')}
            title={t('Sample downloads are disabled in this design preview')}
          >
            <Download size={16} aria-hidden='true' />
            {t('Download')}
          </button>
        </div>
      </div>
      <div className='studio-sample-strip'>
        <div className='studio-sample-strip-heading'>
          <h3>{t('Sample inspiration')}</h3>
          <span>
            {t('Fixed demo media · Not generated by the selected model')}
          </span>
        </div>
        <div className='studio-sample-thumbnails'>
          {isImage &&
            DEMO_IMAGE_SAMPLES.map((item, index) => (
              <button
                key={item.id}
                type='button'
                aria-pressed={selected === index}
                aria-label={t('Preview sample: {{title}}', {
                  title: t(item.title),
                })}
                onClick={() => setSelected(index)}
              >
                <img
                  src={item.src}
                  alt=''
                  width={96}
                  height={76}
                  loading='lazy'
                />
              </button>
            ))}
          <button
            type='button'
            className='studio-more-works'
            onClick={props.onOpenWorks}
          >
            <MoreHorizontal size={21} aria-hidden='true' />
            <span>{t('More works')}</span>
          </button>
        </div>
      </div>
    </section>
  )
}
