server {
    listen 443 ssl http2;
    server_name studio.linoroute.com;
    ssl_certificate /etc/letsencrypt/live/studio.linoroute.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/studio.linoroute.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:studio_ssl:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    if ($host != studio.linoroute.com) { return 421; }
    include /etc/nginx/linoroute-studio/nginx-site.conf;
}
